FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    openfpgaloader \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

ENTRYPOINT ["openFPGALoader", "-b", "nexys_a7_50"]
CMD ["HelloWorld.bit"]
